import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import SideNav from "./_components/SideNav";
import Provider from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
      </head>
      <body className={inter.className}>
        <Header/>
        <div className="w-48 fixed">
          <SideNav/>
        </div>
        <div className="ml-48">
        <Provider>
        {children}
        </Provider>
        </div>
        </body>
    </html>
  );
}
